version: '3.8'

services:
  chat-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: mega-services:bootcamp-endpoint
    ports:
      - "8888:8888"
    networks:
      - mega-network
    restart: unless-stopped
    environment:
      - API_ENDPOINT=/v1/chat/bootcamp
    labels:
      - "com.opea.service=chat"
      - "com.opea.endpoint=/v1/chat/bootcamp"
      - "com.opea.description=OPEA Chat Bootcamp Service"

networks:
  mega-network:
    driver: bridge
